# Site settings
title: Team.201
description: Software Development Team
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Team.201
user_description: 
user_title: Software Development Team
email: dbg@kakao.com
twitter_username: _201t
github_username:  201c
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
